### ISSUE TITLE
make the buttons relative

### ISSUE THREAD

**Issue by SsamuelGit** [SsamuelGit/simplesnakegame-2.0#2]
The buttons for: "settings", "play", and "about us" aren't relative. If I shrink the website, the buttons will hide. Please use flexbox or a similar css instruction.

**Comment by theDEVpro0** [comment]
This is not posible with the animations for the buttons, but the size should fit in every regular screeen-size (except you run the html-file on a gameboy-screen or a potato 😅)

**Comment by SsamuelGit** [comment]
potato ;-)
